name: Test

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Compile
        run: npm run compile

      - name: Unit tests with coverage
        run: npm run test:coverage

      - name: Integration tests
        run: xvfb-run -a npm run test:integration
        if: runner.os == 'Linux'

      - name: Integration tests
        run: npm run test:integration
        if: runner.os != 'Linux'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage/lcov.info
          flags: ${{ matrix.os }}
          name: coverage-${{ matrix.os }}
